/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import faultlocalization.FaultLocalization;
import java.io.*;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.Hashtable;
import java.util.Iterator;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;
import java.util.SortedSet;
import java.util.TreeMap;
import java.util.TreeSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;

/**
 *
 * @author Karini
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lEcobertura = new javax.swing.JLabel();
        abrEcobertura = new javax.swing.JButton();
        lJunit = new javax.swing.JLabel();
        arqJunit = new javax.swing.JTextField();
        abrJunit = new javax.swing.JButton();
        lheuristica = new javax.swing.JLabel();
        btnExecutar = new javax.swing.JButton();
        lJxr = new javax.swing.JLabel();
        arqJxr = new javax.swing.JTextField();
        abrJxr = new javax.swing.JButton();
        arqEcobertura = new javax.swing.JTextField();
        csTarantula = new javax.swing.JCheckBox();
        csOchiai = new javax.swing.JCheckBox();
        csJaccard = new javax.swing.JCheckBox();
        csSBI = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Localizador de Defeitos");
        setName("principal"); // NOI18N

        lEcobertura.setText("Cobertura:");

        abrEcobertura.setBackground(new java.awt.Color(204, 204, 255));
        abrEcobertura.setText("Abrir");
        abrEcobertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrEcoberturaActionPerformed(evt);
            }
        });

        lJunit.setText("Junit:");

        abrJunit.setBackground(new java.awt.Color(204, 204, 255));
        abrJunit.setText("Abrir");
        abrJunit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrJunitActionPerformed(evt);
            }
        });

        lheuristica.setBackground(new java.awt.Color(255, 255, 255));
        lheuristica.setText("Heurística:");

        btnExecutar.setBackground(new java.awt.Color(153, 204, 255));
        btnExecutar.setText("Executar");
        btnExecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecutarActionPerformed(evt);
            }
        });

        lJxr.setText("Jxr:");

        abrJxr.setBackground(new java.awt.Color(204, 204, 255));
        abrJxr.setText("Abrir");
        abrJxr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrJxrActionPerformed(evt);
            }
        });

        csTarantula.setText("Tarantula");
        csTarantula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csTarantulaActionPerformed(evt);
            }
        });

        csOchiai.setText("Ochiai");

        csJaccard.setText("Jaccard");

        csSBI.setText("SBI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arqJxr)
                            .addComponent(arqJunit)
                            .addComponent(arqEcobertura)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lheuristica)
                                    .addComponent(csTarantula)
                                    .addComponent(csSBI))
                                .addGap(0, 370, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(abrJunit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(abrEcobertura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExecutar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(abrJxr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(csJaccard)
                            .addComponent(lEcobertura)
                            .addComponent(lJunit)
                            .addComponent(lJxr)
                            .addComponent(csOchiai))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lEcobertura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abrEcobertura)
                    .addComponent(arqEcobertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lJunit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arqJunit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abrJunit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lJxr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arqJxr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abrJxr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lheuristica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(csTarantula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(csOchiai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(csJaccard)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnExecutar))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(csSBI)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public File ecobertura;
    public File junit;
    public File jxr;
    private Document document;
    private String elementos;           // elementos para escrever no arquivo txt
    private Interface parserHtmlJunit;
    private Interface parserHtmlEcobertura;
    private Interface parserHtmlJxr;
    //private Hashtable prob = new Hashtable();
    private TreeMap<Integer, Double> probTar = new TreeMap<>();
    private TreeMap<Integer, Double> probOch = new TreeMap<>();
    private TreeMap<Integer, Double> probJac = new TreeMap<>();
    private TreeMap<Integer, Double> probSbi = new TreeMap<>();
    private Map<String, ArrayList<Integer>> linhas = new TreeMap();  // armazena e classe e as linhas cobertas da classe
    private ArrayList<String> classes = new ArrayList<>();
    private ArrayList<String> files = new ArrayList<>();    // armazena a lista de arquivos do diretório
    private Junit lerJunit;
    private Ecobertura lerEcob;
    private Jxr lerJxr;
    private FaultLocalization heuristicas;

    public Interface(Document document) {
        this.document = document;
    }

    public Document leituraHtml(String file) throws IOException {
        File leitura = new File(file);
        Document document = Jsoup.parse(leitura, null);
        return document;
    }

    public Document getDocument() {
        return document;
    }


    private void abrJunitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrJunitActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int i = file.showSaveDialog(null);
        if (i == 1) {
            arqJunit.setText("");
        } else {
            junit = file.getSelectedFile();
            arqJunit.setText(junit.getPath());
        }
    }//GEN-LAST:event_abrJunitActionPerformed

    private void abrEcoberturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrEcoberturaActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int i = file.showSaveDialog(null);
        if (i == 1) {
            arqEcobertura.setText("");
        } else {
            ecobertura = file.getSelectedFile();   // seleciona um arquivo na caixa de dialogo
            arqEcobertura.setText(ecobertura.getPath()); // escreve o endereço do arquivo na caixa de texto    

        }
    }//GEN-LAST:event_abrEcoberturaActionPerformed

    private void abrJxrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrJxrActionPerformed
        // TODO add your handling code here:
        JFileChooser caminho = new JFileChooser();
        caminho.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int i = caminho.showSaveDialog(null);
        if (i == 1) {
            arqJxr.setText("");
        } else {
            jxr = caminho.getSelectedFile();   // seleciona um arquivo na caixa de dialogo
            arqJxr.setText(jxr.getPath()); // escreve o endereço do arquivo na caixa de texto
        }
    }//GEN-LAST:event_abrJxrActionPerformed

    private void btnExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecutarActionPerformed
        // TODO add your handling code here:
        double probabilidade;
        JTextArea tar = new JTextArea();
        JTextArea och = new JTextArea();
        JTextArea jac = new JTextArea();
        JTextArea sbi = new JTextArea();

        // Lê Junit
        File fileJunit = new File("C:\\Users\\Karini\\workspace\\myProject\\target\\site\\surefire-report.html");
        //File diretorioJunit = new File(junit.getPath());
        Document documentoJunit;
        try {
            documentoJunit = Jsoup.parse(fileJunit, null);
            Interface parserHtmlJunit = new Interface(documentoJunit);
            lerJunit = new Junit(parserHtmlJunit.document);
            lerJunit.totais();
            lerJunit.testesFalhos();
        } catch (IOException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }

        // ---------------------------- Processa arquivos Ecobertura --------------------------------------
        ArrayList<String> filesEcob = new ArrayList<>();
        //filesEcob = navegar(ecobertura.getPath());
        String path = "C:\\Users\\Karini\\workspace\\myProject\\target\\site\\cobertura";
        navegar(path);
        for (int i = 0; i < files.size(); i++) {
            File fileEcob = new File(files.get(i));
            Document documentoEcob;
            try {
                documentoEcob = Jsoup.parse(fileEcob, null);
                Interface parserHtmlEcob = new Interface(documentoEcob);
                lerEcob = new Ecobertura(parserHtmlEcob.document);
                boolean cobertura = lerEcob.cobertura();
                if (cobertura == true) {            // se o arquivo não cobrir o código fonte -> dispensa arquivo
                    lerEcob.escreveTxt();
                    linhas.put(lerEcob.getClasse(), lerEcob.qtdeLinhasCod());   // armazena e classe e as linhas cobertas da classe
                    classes.add(lerEcob.getClasse());
                }
            } catch (IOException ex) {
                Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        files.clear();

        //----------------------------------- Fim processamento Ecobertura--------------------------------------
        // ----------------------------------Processamento arquivos JXR (código de teste) -----------------------------
        ArrayList<String> filesJxr = new ArrayList<>();
        //filesJxr = navegar(jxr.getPath());
        String arq = "C:\\Users\\Karini\\workspace\\myProject\\target\\site\\xref-test";
        navegar(arq);
        for (int i = 0; i < files.size(); i++) {
            File fileJxr = new File(files.get(i));
            Document documentoJxr;
            try {
                documentoJxr = Jsoup.parse(fileJxr, null);
                Interface parserHtmlJxr = new Interface(documentoJxr);
                lerJxr = new Jxr(parserHtmlJxr.document);
                parserHtmlJxr.elementos = lerJxr.leituraJxr();  // retorna o código do relatório sem lixo
                lerJxr.escreveTxt(parserHtmlJxr.elementos);     // escreve ocódigo em um arquivo TXT para nova leitura
                
                for (String classe : classes) {
                    lerJxr.leTxt(classe);
                }

            } catch (IOException ex) {
                Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        //------------------------------------------ imprime valores do hashtable -----------------------------
        /*Hashtable teste = lerJxr.getInf();
        Set values = teste.entrySet();
        Iterator myIterator = values.iterator();
        System.out.println("Listando arquivos contidos no HashMap myHashMap:");
        while (myIterator.hasNext()) {
            DadosTeste dados = (DadosTeste) ((Entry) myIterator.next()).getValue();
            System.out.println("Classe: " + dados.getClasse() + " MetodoTeste: " + dados.getMetodoTeste()
                    + " Objetos: " + dados.getObjetos() + " MChamados: " + dados.getmChamados() + " Objetos: " + dados.getObjetos());
        }*/
        //---------------------------------- fim impressão hashtable---------------------------------------------
        files.clear();
        //----------------------------------- Fim processamento Jxr -----------------------------------------------

        ArrayList<Double> sucesso = new ArrayList<>();
        ArrayList<Double> falha = new ArrayList<>();
        ArrayList<Double> totSucesso = new ArrayList<>();
        ArrayList<Double> totFalha = new ArrayList<>();
        /*
         Para cada array de linha dentro da treeMap temos que passá-lo para o método falharam
         */
        for (Entry<String, ArrayList<Integer>> entry : linhas.entrySet()) {
            lerEcob.falharam(entry.getValue(), lerJxr, lerJunit);   // pega todos os arraylist contidos em linhas
        }/*falharam*/
            sucesso.add((double) lerEcob.getPassaram());
            falha.add((double) lerEcob.getFalharam());
            totSucesso.add((double) lerJunit.getQtdeSucesso());
            totFalha.add((double) lerJunit.getQtdeFalhas());
            
            for(int i=0; i<sucesso.size(); i++){
                //System.out.println(sucesso.get(i));
            }
        /*}
        if (!csTarantula.isSelected() && !csJaccard.isSelected() && !csOchiai.isSelected() && !csSBI.isSelected()) {
            JOptionPane.showMessageDialog(null, "Selecione uma heurística");
        }
        if (csTarantula.isSelected()) {
            for (int i = 0; i < linhas.size(); i++) {
                heuristicas = new FaultLocalization(sucesso.get(i), falha.get(i), totSucesso.get(i), totFalha.get(i));
                probabilidade = heuristicas.tarantula();
                probTar.put(linhas.get(i), probabilidade);
            }
            entriesSortedByValues(probTar);
            System.out.println(entriesSortedByValues(probTar));
        }
        if (csOchiai.isSelected()) {

            for (int i = 0; i < linhas.size(); i++) {
                heuristicas = new FaultLocalization(sucesso.get(i), falha.get(i), totSucesso.get(i), totFalha.get(i));
                probabilidade = heuristicas.ochiai();
                probOch.put(linhas.get(i), probabilidade);
            }
            System.out.println(entriesSortedByValues(probOch));
        }
        if (csJaccard.isSelected()) {
            for (int i = 0; i < linhas.size(); i++) {
                heuristicas = new FaultLocalization(sucesso.get(i), falha.get(i), totSucesso.get(i), totFalha.get(i));
                probabilidade = heuristicas.jaccard();
                probJac.put(linhas.get(i), probabilidade);
            }
            System.out.println(entriesSortedByValues(probJac));
        }
        if (csSBI.isSelected()) {
            for (int i = 0; i < linhas.size(); i++) {
                heuristicas = new FaultLocalization(sucesso.get(i), falha.get(i), totSucesso.get(i), totFalha.get(i));
                probabilidade = heuristicas.sbi();
                probSbi.put(linhas.get(i), probabilidade);
                //System.out.println("linha: " + linhas.get(i)+ " falha: " + falhasLinha.get(i) + " sucesso: " + sucessoLinha.get(i) );
            }
            System.out.println(entriesSortedByValues(probSbi));
        }
        JanelaResult panel = new JanelaResult();
        panel.setVisible(true);*/
    }//GEN-LAST:event_btnExecutarActionPerformed

    public void navegar(String caminho) {
        File diretorio = new File(caminho);
        for (File file : diretorio.listFiles()) {
            if (file.isFile()) {
                if (!file.getName().startsWith("frame") && !file.getName().startsWith("index")
                        && !file.getName().startsWith("help") && !file.getName().startsWith("package")
                        && !file.getName().startsWith("allclasses") && !file.getName().startsWith("overview")
                        && !file.getName().startsWith("stylesheet")) {
                    files.add(caminho + "\\" + file.getName());
                }
            } else if ((!file.getName().equals("css") && !file.getName().equals("images") && !file.getName().equals("js"))) {
                //System.out.println("DIRETORIO: " + file.getName());
                navegar(caminho + "\\" + file.getName());
            }
        }
    }

    static <K, V extends Comparable<? super V>>
            SortedSet<Map.Entry<K, V>> entriesSortedByValues(Map<K, V> map) {
        SortedSet<Map.Entry<K, V>> sortedEntries;
        sortedEntries = new TreeSet<Map.Entry<K, V>>(
                new Comparator<Map.Entry<K, V>>() {
                    @Override
                    public int compare(Map.Entry<K, V> e1, Map.Entry<K, V> e2) {
                        int res = e1.getValue().compareTo(e2.getValue());
                        return res != 0 ? res : 1;
                    }
                }
        );
        sortedEntries.addAll(map.entrySet());
        return sortedEntries;
    }


    private void csTarantulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csTarantulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_csTarantulaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrEcobertura;
    private javax.swing.JButton abrJunit;
    private javax.swing.JButton abrJxr;
    private javax.swing.JTextField arqEcobertura;
    private javax.swing.JTextField arqJunit;
    private javax.swing.JTextField arqJxr;
    private javax.swing.JButton btnExecutar;
    private javax.swing.JCheckBox csJaccard;
    private javax.swing.JCheckBox csOchiai;
    private javax.swing.JCheckBox csSBI;
    private javax.swing.JCheckBox csTarantula;
    private javax.swing.JLabel lEcobertura;
    private javax.swing.JLabel lJunit;
    private javax.swing.JLabel lJxr;
    private javax.swing.JLabel lheuristica;
    // End of variables declaration//GEN-END:variables

}
