/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import javax.swing.JTextArea;

/**
 *
 * @author Karini
 */
public class JanelaResult extends javax.swing.JFrame {

    /**
     * Creates new form JanelaResult
     */
    public JanelaResult() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ctTarantula = new javax.swing.JTextArea();
        lpTarantula = new javax.swing.JLabel();
        lpInf = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ctOchiai = new javax.swing.JTextArea();
        lpOchiai = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ctJaccard = new javax.swing.JTextArea();
        lpJaccard = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ctSbi = new javax.swing.JTextArea();
        lpSbi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ctTarantula.setColumns(20);
        ctTarantula.setRows(5);
        jScrollPane1.setViewportView(ctTarantula);

        lpTarantula.setText("Tarantula:");

        lpInf.setText("Leitura: Linha -> Probabilidade");

        ctOchiai.setColumns(20);
        ctOchiai.setRows(5);
        jScrollPane2.setViewportView(ctOchiai);

        lpOchiai.setText("Ochiai:");

        ctJaccard.setColumns(20);
        ctJaccard.setRows(5);
        jScrollPane3.setViewportView(ctJaccard);

        lpJaccard.setText("Jaccard:");

        ctSbi.setColumns(20);
        ctSbi.setRows(5);
        jScrollPane4.setViewportView(ctSbi);

        lpSbi.setText("SBI:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lpInf)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lpTarantula))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lpOchiai))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lpJaccard))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lpSbi)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lpInf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lpTarantula)
                    .addComponent(lpOchiai)
                    .addComponent(lpJaccard)
                    .addComponent(lpSbi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaResult().setVisible(true);
            }
            
            
        });
    }

    public void setCtJaccard(JTextArea ctJaccard) {
        this.ctJaccard = ctJaccard;
    }

    public void setCtOchiai(JTextArea ctOchiai) {
        this.ctOchiai = ctOchiai;
    }

    public void setCtTarantula(JTextArea ctTarantula) {
        this.ctTarantula = ctTarantula;
    }

    public void setCtSbi(JTextArea ctSbi) {
        this.ctSbi = ctSbi;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ctJaccard;
    private javax.swing.JTextArea ctOchiai;
    private javax.swing.JTextArea ctSbi;
    private javax.swing.JTextArea ctTarantula;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lpInf;
    private javax.swing.JLabel lpJaccard;
    private javax.swing.JLabel lpOchiai;
    private javax.swing.JLabel lpSbi;
    private javax.swing.JLabel lpTarantula;
    // End of variables declaration//GEN-END:variables
}
